/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                  '#99f7ff',
        'primary-container':        '#00f1fe',
        'secondary':                '#00e0fe',
        'secondary-container':      '#006877',
        'secondary-dim':            '#00d1ed',
        'tertiary':                 '#69b2ff',
        'tertiary-container':       '#4aa5fb',
        'background':               '#001114',
        'surface':                  '#001114',
        'surface-container':        '#001d22',
        'surface-container-low':    '#00161b',
        'surface-container-high':   '#00242a',
        'surface-container-lowest': '#000000',
        'on-background':            '#b7eefb',
        'on-surface':               '#b7eefb',
        'on-surface-variant':       '#7eb4bf',
        'on-primary-container':     '#00555b',
        'on-secondary-container':   '#eafbff',
        'outline':                  '#477d88',
        'outline-variant':          '#114f59',
        'error':                    '#ff716c',
        'error-container':          '#9f0519',
        'on-error':                 '#490006',
        'on-error-container':       '#ffa8a3',
      },
      fontFamily: {
        display: ['Space Grotesk'],
        body:    ['Inter'],
      },
    },
  },
  plugins: [],
}
